# Generated by Django 3.2.4 on 2023-01-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20221216_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='courseid',
            new_name='courseID',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='studentid',
            new_name='studentID',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sudentNumber',
            new_name='studentNumber',
        ),
    ]
