# Generated by Django 3.2.4 on 2023-01-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20230127_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, default='default-course.jpg', null=True, upload_to=''),
        ),
    ]
